import {
  ADMIN_CONSOLE_APP_CODE,
  ADMIN_CONSOLE_PERMISSION_CODES,
  FILE_SERVER_APP_CODE,
  FILE_SERVER_PERMISSION_CODES,
  PROJECT_APP_CODE,
  PROJECT_PERMISSION_CODES,
  type AuthorizationResourceType,
  type CompatibilityUserRole,
} from '@super-pro/shared-types';

export interface SeedPermissionDefinition {
  code: string;
  appCode: string;
  resourceType: AuthorizationResourceType;
  resourceCode: string;
  action: string;
  name: string;
  description: string;
}

export interface SeedRoleDefinition {
  code: string;
  name: string;
  description: string;
}

export interface SeedProjectDefinition {
  projectCode: string;
  projectName: string;
  remark?: string;
  aliases?: readonly string[];
}

export const SEEDED_PERMISSIONS: readonly SeedPermissionDefinition[] = [
  {
    code: '*.*.*',
    appCode: '*',
    resourceType: 'api',
    resourceCode: '*',
    action: '*',
    name: '超级管理员全部权限',
    description: '拥有所有项目、所有项目下的权限和所有行为的全部权限。',
  },
  {
    code: FILE_SERVER_PERMISSION_CODES.treeRead,
    appCode: FILE_SERVER_APP_CODE,
    resourceType: 'api',
    resourceCode: 'tree',
    action: 'read',
    name: '文件树读取',
    description: '允许读取 file-server 文件树和目录结构。',
  },
  {
    code: FILE_SERVER_PERMISSION_CODES.previewRead,
    appCode: FILE_SERVER_APP_CODE,
    resourceType: 'api',
    resourceCode: 'preview',
    action: 'read',
    name: '文件预览',
    description: '允许读取 file-server 文件预览内容。',
  },
  {
    code: FILE_SERVER_PERMISSION_CODES.downloadRead,
    appCode: FILE_SERVER_APP_CODE,
    resourceType: 'api',
    resourceCode: 'download',
    action: 'read',
    name: '文件下载',
    description: '允许下载 file-server 文件内容。',
  },
  {
    code: FILE_SERVER_PERMISSION_CODES.folderCreate,
    appCode: FILE_SERVER_APP_CODE,
    resourceType: 'button',
    resourceCode: 'folder',
    action: 'create',
    name: '新建文件夹',
    description: '允许在 file-server 中创建文件夹。',
  },
  {
    code: FILE_SERVER_PERMISSION_CODES.fileUpload,
    appCode: FILE_SERVER_APP_CODE,
    resourceType: 'button',
    resourceCode: 'file',
    action: 'upload',
    name: '上传文件',
    description: '允许在 file-server 中上传文件或文件夹。',
  },
  {
    code: FILE_SERVER_PERMISSION_CODES.fileDelete,
    appCode: FILE_SERVER_APP_CODE,
    resourceType: 'button',
    resourceCode: 'file',
    action: 'delete',
    name: '删除文件',
    description: '允许在 file-server 中删除文件或文件夹。',
  },
  {
    code: FILE_SERVER_PERMISSION_CODES.fileMove,
    appCode: FILE_SERVER_APP_CODE,
    resourceType: 'button',
    resourceCode: 'file',
    action: 'move',
    name: '移动文件',
    description: '允许在 file-server 中拖拽移动文件或文件夹。',
  },
  {
    code: PROJECT_PERMISSION_CODES.projectRead,
    appCode: PROJECT_APP_CODE,
    resourceType: 'api',
    resourceCode: 'project',
    action: 'read',
    name: '项目查看',
    description: '允许查看项目列表和项目详情。',
  },
  {
    code: PROJECT_PERMISSION_CODES.projectCreate,
    appCode: PROJECT_APP_CODE,
    resourceType: 'button',
    resourceCode: 'project',
    action: 'create',
    name: '项目新增',
    description: '允许新增项目。',
  },
  {
    code: PROJECT_PERMISSION_CODES.projectUpdate,
    appCode: PROJECT_APP_CODE,
    resourceType: 'button',
    resourceCode: 'project',
    action: 'update',
    name: '项目编辑',
    description: '允许修改项目信息。',
  },
  {
    code: PROJECT_PERMISSION_CODES.projectDelete,
    appCode: PROJECT_APP_CODE,
    resourceType: 'button',
    resourceCode: 'project',
    action: 'delete',
    name: '项目删除',
    description: '允许删除项目。',
  },
  {
    code: ADMIN_CONSOLE_PERMISSION_CODES.dashboardMenuView,
    appCode: ADMIN_CONSOLE_APP_CODE,
    resourceType: 'menu',
    resourceCode: 'dashboard',
    action: 'view',
    name: '工作台可见',
    description: '允许查看管理后台工作台页面。',
  },
  {
    code: ADMIN_CONSOLE_PERMISSION_CODES.usersMenuView,
    appCode: ADMIN_CONSOLE_APP_CODE,
    resourceType: 'menu',
    resourceCode: 'users',
    action: 'view',
    name: '用户管理可见',
    description: '允许查看管理后台用户管理页面。',
  },
  {
    code: ADMIN_CONSOLE_PERMISSION_CODES.rolesMenuView,
    appCode: ADMIN_CONSOLE_APP_CODE,
    resourceType: 'menu',
    resourceCode: 'roles',
    action: 'view',
    name: '角色管理可见',
    description: '允许查看管理后台角色管理页面。',
  },
  {
    code: ADMIN_CONSOLE_PERMISSION_CODES.permissionsMenuView,
    appCode: ADMIN_CONSOLE_APP_CODE,
    resourceType: 'menu',
    resourceCode: 'permissions',
    action: 'view',
    name: '权限管理可见',
    description: '允许查看管理后台权限管理页面。',
  },
  {
    code: ADMIN_CONSOLE_PERMISSION_CODES.projectsMenuView,
    appCode: ADMIN_CONSOLE_APP_CODE,
    resourceType: 'menu',
    resourceCode: 'projects',
    action: 'view',
    name: '项目管理可见',
    description: '允许查看管理后台项目管理页面。',
  },
  {
    code: ADMIN_CONSOLE_PERMISSION_CODES.todosMenuView,
    appCode: ADMIN_CONSOLE_APP_CODE,
    resourceType: 'menu',
    resourceCode: 'todos',
    action: 'view',
    name: '\u5f85\u529e\u7ba1\u7406\u53ef\u89c1',
    description: '\u5141\u8bb8\u67e5\u770b\u7ba1\u7406\u540e\u53f0\u5f85\u529e\u7ba1\u7406\u9875\u9762\u3002',
  },
  {
    code: ADMIN_CONSOLE_PERMISSION_CODES.reportsMenuView,
    appCode: ADMIN_CONSOLE_APP_CODE,
    resourceType: 'menu',
    resourceCode: 'reports',
    action: 'view',
    name: 'BMS 菜单可见',
    description: '允许查看管理后台 BMS 菜单页面。',
  },
  {
    code: ADMIN_CONSOLE_PERMISSION_CODES.settingsMenuView,
    appCode: ADMIN_CONSOLE_APP_CODE,
    resourceType: 'menu',
    resourceCode: 'settings',
    action: 'view',
    name: '站点菜单可见',
    description: '允许查看管理后台站点菜单页面。',
  },
  {
    code: ADMIN_CONSOLE_PERMISSION_CODES.roleCreate,
    appCode: ADMIN_CONSOLE_APP_CODE,
    resourceType: 'button',
    resourceCode: 'roles',
    action: 'create',
    name: '新增角色',
    description: '允许在管理后台新增角色。',
  },
  {
    code: ADMIN_CONSOLE_PERMISSION_CODES.roleUpdate,
    appCode: ADMIN_CONSOLE_APP_CODE,
    resourceType: 'button',
    resourceCode: 'roles',
    action: 'update',
    name: '修改角色',
    description: '允许在管理后台修改角色。',
  },
  {
    code: ADMIN_CONSOLE_PERMISSION_CODES.roleDelete,
    appCode: ADMIN_CONSOLE_APP_CODE,
    resourceType: 'button',
    resourceCode: 'roles',
    action: 'delete',
    name: '删除角色',
    description: '允许在管理后台删除角色。',
  },
  {
    code: ADMIN_CONSOLE_PERMISSION_CODES.roleAssign,
    appCode: ADMIN_CONSOLE_APP_CODE,
    resourceType: 'button',
    resourceCode: 'roles',
    action: 'assign',
    name: '分配角色权限',
    description: '允许在管理后台为角色分配权限。',
  },
  {
    code: ADMIN_CONSOLE_PERMISSION_CODES.permissionCreate,
    appCode: ADMIN_CONSOLE_APP_CODE,
    resourceType: 'button',
    resourceCode: 'permissions',
    action: 'create',
    name: '新增权限',
    description: '允许在管理后台新增权限。',
  },
  {
    code: ADMIN_CONSOLE_PERMISSION_CODES.permissionUpdate,
    appCode: ADMIN_CONSOLE_APP_CODE,
    resourceType: 'button',
    resourceCode: 'permissions',
    action: 'update',
    name: '修改权限',
    description: '允许在管理后台修改权限。',
  },
  {
    code: ADMIN_CONSOLE_PERMISSION_CODES.permissionDelete,
    appCode: ADMIN_CONSOLE_APP_CODE,
    resourceType: 'button',
    resourceCode: 'permissions',
    action: 'delete',
    name: '删除权限',
    description: '允许在管理后台删除权限。',
  },
  {
    code: ADMIN_CONSOLE_PERMISSION_CODES.projectCreate,
    appCode: ADMIN_CONSOLE_APP_CODE,
    resourceType: 'button',
    resourceCode: 'projects',
    action: 'create',
    name: '新增项目',
    description: '允许在管理后台新增项目。',
  },
  {
    code: ADMIN_CONSOLE_PERMISSION_CODES.projectUpdate,
    appCode: ADMIN_CONSOLE_APP_CODE,
    resourceType: 'button',
    resourceCode: 'projects',
    action: 'update',
    name: '修改项目',
    description: '允许在管理后台修改项目。',
  },
  {
    code: ADMIN_CONSOLE_PERMISSION_CODES.projectDelete,
    appCode: ADMIN_CONSOLE_APP_CODE,
    resourceType: 'button',
    resourceCode: 'projects',
    action: 'delete',
    name: '删除项目',
    description: '允许在管理后台删除项目。',
  },
  {
    code: ADMIN_CONSOLE_PERMISSION_CODES.todoCreate,
    appCode: ADMIN_CONSOLE_APP_CODE,
    resourceType: 'button',
    resourceCode: 'todos',
    action: 'create',
    name: '\u65b0\u589e\u5f85\u529e',
    description: '\u5141\u8bb8\u5728\u7ba1\u7406\u540e\u53f0\u65b0\u589e\u5f85\u529e\u4efb\u52a1\u3002',
  },
  {
    code: ADMIN_CONSOLE_PERMISSION_CODES.todoUpdate,
    appCode: ADMIN_CONSOLE_APP_CODE,
    resourceType: 'button',
    resourceCode: 'todos',
    action: 'update',
    name: '\u4fee\u6539\u5f85\u529e',
    description: '\u5141\u8bb8\u5728\u7ba1\u7406\u540e\u53f0\u4fee\u6539\u5f85\u529e\u4fe1\u606f\u3002',
  },
  {
    code: ADMIN_CONSOLE_PERMISSION_CODES.todoDelete,
    appCode: ADMIN_CONSOLE_APP_CODE,
    resourceType: 'button',
    resourceCode: 'todos',
    action: 'delete',
    name: '\u5220\u9664\u5f85\u529e',
    description: '\u5141\u8bb8\u5728\u7ba1\u7406\u540e\u53f0\u5220\u9664\u5f85\u529e\u4efb\u52a1\u3002',
  },
  {
    code: ADMIN_CONSOLE_PERMISSION_CODES.reportCreate,
    appCode: ADMIN_CONSOLE_APP_CODE,
    resourceType: 'button',
    resourceCode: 'reports',
    action: 'create',
    name: '新增 BMS 菜单',
    description: '允许在管理后台新增 BMS 菜单。',
  },
  {
    code: ADMIN_CONSOLE_PERMISSION_CODES.reportUpdate,
    appCode: ADMIN_CONSOLE_APP_CODE,
    resourceType: 'button',
    resourceCode: 'reports',
    action: 'update',
    name: '修改 BMS 菜单',
    description: '允许在管理后台修改 BMS 菜单。',
  },
  {
    code: ADMIN_CONSOLE_PERMISSION_CODES.reportDelete,
    appCode: ADMIN_CONSOLE_APP_CODE,
    resourceType: 'button',
    resourceCode: 'reports',
    action: 'delete',
    name: '删除 BMS 菜单',
    description: '允许在管理后台删除 BMS 菜单。',
  },
  {
    code: ADMIN_CONSOLE_PERMISSION_CODES.settingCreate,
    appCode: ADMIN_CONSOLE_APP_CODE,
    resourceType: 'button',
    resourceCode: 'settings',
    action: 'create',
    name: '新增站点菜单',
    description: '允许在管理后台新增站点菜单。',
  },
  {
    code: ADMIN_CONSOLE_PERMISSION_CODES.settingUpdate,
    appCode: ADMIN_CONSOLE_APP_CODE,
    resourceType: 'button',
    resourceCode: 'settings',
    action: 'update',
    name: '修改站点菜单',
    description: '允许在管理后台修改站点菜单。',
  },
  {
    code: ADMIN_CONSOLE_PERMISSION_CODES.settingDelete,
    appCode: ADMIN_CONSOLE_APP_CODE,
    resourceType: 'button',
    resourceCode: 'settings',
    action: 'delete',
    name: '删除站点菜单',
    description: '允许在管理后台删除站点菜单。',
  },
  {
    code: ADMIN_CONSOLE_PERMISSION_CODES.rolesApiRead,
    appCode: ADMIN_CONSOLE_APP_CODE,
    resourceType: 'api',
    resourceCode: 'roles',
    action: 'read',
    name: '角色接口查看',
    description: '允许调用管理后台角色查询接口。',
  },
  {
    code: ADMIN_CONSOLE_PERMISSION_CODES.rolesApiCreate,
    appCode: ADMIN_CONSOLE_APP_CODE,
    resourceType: 'api',
    resourceCode: 'roles',
    action: 'create',
    name: '角色接口新增',
    description: '允许调用管理后台角色新增接口。',
  },
  {
    code: ADMIN_CONSOLE_PERMISSION_CODES.rolesApiUpdate,
    appCode: ADMIN_CONSOLE_APP_CODE,
    resourceType: 'api',
    resourceCode: 'roles',
    action: 'update',
    name: '角色接口修改',
    description: '允许调用管理后台角色修改接口。',
  },
  {
    code: ADMIN_CONSOLE_PERMISSION_CODES.rolesApiDelete,
    appCode: ADMIN_CONSOLE_APP_CODE,
    resourceType: 'api',
    resourceCode: 'roles',
    action: 'delete',
    name: '角色接口删除',
    description: '允许调用管理后台角色删除接口。',
  },
  {
    code: ADMIN_CONSOLE_PERMISSION_CODES.permissionsApiRead,
    appCode: ADMIN_CONSOLE_APP_CODE,
    resourceType: 'api',
    resourceCode: 'permissions',
    action: 'read',
    name: '权限接口查看',
    description: '允许调用管理后台权限查询接口。',
  },
  {
    code: ADMIN_CONSOLE_PERMISSION_CODES.permissionsApiCreate,
    appCode: ADMIN_CONSOLE_APP_CODE,
    resourceType: 'api',
    resourceCode: 'permissions',
    action: 'create',
    name: '权限接口新增',
    description: '允许调用管理后台权限新增接口。',
  },
  {
    code: ADMIN_CONSOLE_PERMISSION_CODES.permissionsApiUpdate,
    appCode: ADMIN_CONSOLE_APP_CODE,
    resourceType: 'api',
    resourceCode: 'permissions',
    action: 'update',
    name: '权限接口修改',
    description: '允许调用管理后台权限修改接口。',
  },
  {
    code: ADMIN_CONSOLE_PERMISSION_CODES.permissionsApiDelete,
    appCode: ADMIN_CONSOLE_APP_CODE,
    resourceType: 'api',
    resourceCode: 'permissions',
    action: 'delete',
    name: '权限接口删除',
    description: '允许调用管理后台权限删除接口。',
  },
  {
    code: ADMIN_CONSOLE_PERMISSION_CODES.adminMenuApiRead,
    appCode: ADMIN_CONSOLE_APP_CODE,
    resourceType: 'api',
    resourceCode: 'admin-menu',
    action: 'read',
    name: 'BMS 菜单接口查看',
    description: '允许调用 BMS 菜单查询接口。',
  },
  {
    code: ADMIN_CONSOLE_PERMISSION_CODES.adminMenuApiCreate,
    appCode: ADMIN_CONSOLE_APP_CODE,
    resourceType: 'api',
    resourceCode: 'admin-menu',
    action: 'create',
    name: 'BMS 菜单接口新增',
    description: '允许调用 BMS 菜单新增接口。',
  },
  {
    code: ADMIN_CONSOLE_PERMISSION_CODES.adminMenuApiUpdate,
    appCode: ADMIN_CONSOLE_APP_CODE,
    resourceType: 'api',
    resourceCode: 'admin-menu',
    action: 'update',
    name: 'BMS 菜单接口修改',
    description: '允许调用 BMS 菜单修改接口。',
  },
  {
    code: ADMIN_CONSOLE_PERMISSION_CODES.adminMenuApiDelete,
    appCode: ADMIN_CONSOLE_APP_CODE,
    resourceType: 'api',
    resourceCode: 'admin-menu',
    action: 'delete',
    name: 'BMS 菜单接口删除',
    description: '允许调用 BMS 菜单删除接口。',
  },
  {
    code: ADMIN_CONSOLE_PERMISSION_CODES.todosApiRead,
    appCode: ADMIN_CONSOLE_APP_CODE,
    resourceType: 'api',
    resourceCode: 'todos',
    action: 'read',
    name: '\u5f85\u529e\u63a5\u53e3\u67e5\u770b',
    description: '\u5141\u8bb8\u8c03\u7528\u7ba1\u7406\u540e\u53f0\u5f85\u529e\u67e5\u8be2\u63a5\u53e3\u3002',
  },
  {
    code: ADMIN_CONSOLE_PERMISSION_CODES.todosApiCreate,
    appCode: ADMIN_CONSOLE_APP_CODE,
    resourceType: 'api',
    resourceCode: 'todos',
    action: 'create',
    name: '\u5f85\u529e\u63a5\u53e3\u65b0\u589e',
    description: '\u5141\u8bb8\u8c03\u7528\u7ba1\u7406\u540e\u53f0\u5f85\u529e\u65b0\u589e\u63a5\u53e3\u3002',
  },
  {
    code: ADMIN_CONSOLE_PERMISSION_CODES.todosApiUpdate,
    appCode: ADMIN_CONSOLE_APP_CODE,
    resourceType: 'api',
    resourceCode: 'todos',
    action: 'update',
    name: '\u5f85\u529e\u63a5\u53e3\u4fee\u6539',
    description: '\u5141\u8bb8\u8c03\u7528\u7ba1\u7406\u540e\u53f0\u5f85\u529e\u4fee\u6539\u63a5\u53e3\u3002',
  },
  {
    code: ADMIN_CONSOLE_PERMISSION_CODES.todosApiDelete,
    appCode: ADMIN_CONSOLE_APP_CODE,
    resourceType: 'api',
    resourceCode: 'todos',
    action: 'delete',
    name: '\u5f85\u529e\u63a5\u53e3\u5220\u9664',
    description: '\u5141\u8bb8\u8c03\u7528\u7ba1\u7406\u540e\u53f0\u5f85\u529e\u5220\u9664\u63a5\u53e3\u3002',
  },
  {
    code: ADMIN_CONSOLE_PERMISSION_CODES.siteMenuApiRead,
    appCode: ADMIN_CONSOLE_APP_CODE,
    resourceType: 'api',
    resourceCode: 'site-menu',
    action: 'read',
    name: '站点菜单接口查看',
    description: '允许调用站点菜单查询接口。',
  },
  {
    code: ADMIN_CONSOLE_PERMISSION_CODES.siteMenuApiCreate,
    appCode: ADMIN_CONSOLE_APP_CODE,
    resourceType: 'api',
    resourceCode: 'site-menu',
    action: 'create',
    name: '站点菜单接口新增',
    description: '允许调用站点菜单新增接口。',
  },
  {
    code: ADMIN_CONSOLE_PERMISSION_CODES.siteMenuApiUpdate,
    appCode: ADMIN_CONSOLE_APP_CODE,
    resourceType: 'api',
    resourceCode: 'site-menu',
    action: 'update',
    name: '站点菜单接口修改',
    description: '允许调用站点菜单修改接口。',
  },
  {
    code: ADMIN_CONSOLE_PERMISSION_CODES.siteMenuApiDelete,
    appCode: ADMIN_CONSOLE_APP_CODE,
    resourceType: 'api',
    resourceCode: 'site-menu',
    action: 'delete',
    name: '站点菜单接口删除',
    description: '允许调用站点菜单删除接口。',
  },
] as const;

export const SEEDED_ROLES: readonly SeedRoleDefinition[] = [
  {
    code: 'platform.admin',
    name: '平台管理员',
    description: '平台权限试点管理员，默认拥有 file-server、project 与 admin-console 的全部权限。',
  },
  {
    code: 'file-server.viewer',
    name: '文件服务只读',
    description: '允许查看 file-server 文件树、预览和下载内容。',
  },
  {
    code: 'file-server.editor',
    name: '文件服务编辑',
    description: '允许执行 file-server 试点中的全部文件操作。',
  },
  {
    code: 'project.viewer',
    name: '项目管理只读',
    description: '允许查看 project 模块的项目列表与详情。',
  },
  {
    code: 'project.editor',
    name: '项目管理编辑',
    description: '允许执行 project 模块的项目新增、修改和删除。',
  },
  {
    code: 'admin-console.viewer',
    name: '管理后台只读',
    description: '允许查看管理后台的导航和基础页面。',
  },
  {
    code: 'admin-console.editor',
    name: '管理后台编辑',
    description: '允许执行管理后台中和权限、项目、菜单相关的编辑操作。',
  },
] as const;

export const SEEDED_PROJECTS: readonly SeedProjectDefinition[] = [
  {
    projectCode: FILE_SERVER_APP_CODE,
    projectName: '文件管理系统',
    remark: '权限定义中的 file-server 标准项目编码。',
  },
  {
    projectCode: PROJECT_APP_CODE,
    projectName: '项目中心',
    remark: '权限定义中的 project 标准项目编码。',
  },
  {
    projectCode: ADMIN_CONSOLE_APP_CODE,
    projectName: '后台管理系统',
    remark: '权限定义中的 admin-console 标准项目编码。',
    aliases: ['BMS'],
  },
] as const;

export const SEEDED_ROLE_PERMISSION_CODES: Readonly<Record<string, readonly string[]>> = {
  'platform.admin': ['*.*.*'],
  'file-server.viewer': [
    FILE_SERVER_PERMISSION_CODES.treeRead,
    FILE_SERVER_PERMISSION_CODES.previewRead,
    FILE_SERVER_PERMISSION_CODES.downloadRead,
  ],
  'file-server.editor': [
    FILE_SERVER_PERMISSION_CODES.treeRead,
    FILE_SERVER_PERMISSION_CODES.previewRead,
    FILE_SERVER_PERMISSION_CODES.downloadRead,
    FILE_SERVER_PERMISSION_CODES.folderCreate,
    FILE_SERVER_PERMISSION_CODES.fileUpload,
    FILE_SERVER_PERMISSION_CODES.fileDelete,
    FILE_SERVER_PERMISSION_CODES.fileMove,
  ],
  'project.viewer': [PROJECT_PERMISSION_CODES.projectRead],
  'project.editor': [
    PROJECT_PERMISSION_CODES.projectRead,
    PROJECT_PERMISSION_CODES.projectCreate,
    PROJECT_PERMISSION_CODES.projectUpdate,
    PROJECT_PERMISSION_CODES.projectDelete,
  ],
  'admin-console.viewer': [
    ADMIN_CONSOLE_PERMISSION_CODES.dashboardMenuView,
    ADMIN_CONSOLE_PERMISSION_CODES.usersMenuView,
    ADMIN_CONSOLE_PERMISSION_CODES.rolesMenuView,
    ADMIN_CONSOLE_PERMISSION_CODES.permissionsMenuView,
    ADMIN_CONSOLE_PERMISSION_CODES.projectsMenuView,
    ADMIN_CONSOLE_PERMISSION_CODES.todosMenuView,
    ADMIN_CONSOLE_PERMISSION_CODES.reportsMenuView,
    ADMIN_CONSOLE_PERMISSION_CODES.settingsMenuView,
    ADMIN_CONSOLE_PERMISSION_CODES.rolesApiRead,
    ADMIN_CONSOLE_PERMISSION_CODES.permissionsApiRead,
    ADMIN_CONSOLE_PERMISSION_CODES.todosApiRead,
    ADMIN_CONSOLE_PERMISSION_CODES.adminMenuApiRead,
    ADMIN_CONSOLE_PERMISSION_CODES.siteMenuApiRead,
  ],
  'admin-console.editor': [
    ADMIN_CONSOLE_PERMISSION_CODES.dashboardMenuView,
    ADMIN_CONSOLE_PERMISSION_CODES.usersMenuView,
    ADMIN_CONSOLE_PERMISSION_CODES.rolesMenuView,
    ADMIN_CONSOLE_PERMISSION_CODES.permissionsMenuView,
    ADMIN_CONSOLE_PERMISSION_CODES.projectsMenuView,
    ADMIN_CONSOLE_PERMISSION_CODES.todosMenuView,
    ADMIN_CONSOLE_PERMISSION_CODES.reportsMenuView,
    ADMIN_CONSOLE_PERMISSION_CODES.settingsMenuView,
    ADMIN_CONSOLE_PERMISSION_CODES.roleCreate,
    ADMIN_CONSOLE_PERMISSION_CODES.roleUpdate,
    ADMIN_CONSOLE_PERMISSION_CODES.roleDelete,
    ADMIN_CONSOLE_PERMISSION_CODES.roleAssign,
    ADMIN_CONSOLE_PERMISSION_CODES.permissionCreate,
    ADMIN_CONSOLE_PERMISSION_CODES.permissionUpdate,
    ADMIN_CONSOLE_PERMISSION_CODES.permissionDelete,
    ADMIN_CONSOLE_PERMISSION_CODES.projectCreate,
    ADMIN_CONSOLE_PERMISSION_CODES.projectUpdate,
    ADMIN_CONSOLE_PERMISSION_CODES.projectDelete,
    ADMIN_CONSOLE_PERMISSION_CODES.todoCreate,
    ADMIN_CONSOLE_PERMISSION_CODES.todoUpdate,
    ADMIN_CONSOLE_PERMISSION_CODES.todoDelete,
    ADMIN_CONSOLE_PERMISSION_CODES.reportCreate,
    ADMIN_CONSOLE_PERMISSION_CODES.reportUpdate,
    ADMIN_CONSOLE_PERMISSION_CODES.reportDelete,
    ADMIN_CONSOLE_PERMISSION_CODES.settingCreate,
    ADMIN_CONSOLE_PERMISSION_CODES.settingUpdate,
    ADMIN_CONSOLE_PERMISSION_CODES.settingDelete,
    ADMIN_CONSOLE_PERMISSION_CODES.rolesApiRead,
    ADMIN_CONSOLE_PERMISSION_CODES.rolesApiCreate,
    ADMIN_CONSOLE_PERMISSION_CODES.rolesApiUpdate,
    ADMIN_CONSOLE_PERMISSION_CODES.rolesApiDelete,
    ADMIN_CONSOLE_PERMISSION_CODES.permissionsApiRead,
    ADMIN_CONSOLE_PERMISSION_CODES.permissionsApiCreate,
    ADMIN_CONSOLE_PERMISSION_CODES.permissionsApiUpdate,
    ADMIN_CONSOLE_PERMISSION_CODES.permissionsApiDelete,
    ADMIN_CONSOLE_PERMISSION_CODES.todosApiRead,
    ADMIN_CONSOLE_PERMISSION_CODES.todosApiCreate,
    ADMIN_CONSOLE_PERMISSION_CODES.todosApiUpdate,
    ADMIN_CONSOLE_PERMISSION_CODES.todosApiDelete,
    ADMIN_CONSOLE_PERMISSION_CODES.adminMenuApiRead,
    ADMIN_CONSOLE_PERMISSION_CODES.adminMenuApiCreate,
    ADMIN_CONSOLE_PERMISSION_CODES.adminMenuApiUpdate,
    ADMIN_CONSOLE_PERMISSION_CODES.adminMenuApiDelete,
    ADMIN_CONSOLE_PERMISSION_CODES.siteMenuApiRead,
    ADMIN_CONSOLE_PERMISSION_CODES.siteMenuApiCreate,
    ADMIN_CONSOLE_PERMISSION_CODES.siteMenuApiUpdate,
    ADMIN_CONSOLE_PERMISSION_CODES.siteMenuApiDelete,
  ],
};

export const COMPATIBILITY_ROLE_FALLBACK_ROLE_CODES: Readonly<
  Record<CompatibilityUserRole, readonly string[]>
> = {
  admin: ['platform.admin'],
  employee: ['file-server.editor', 'project.editor', 'admin-console.editor'],
  approver: ['file-server.editor', 'project.editor', 'admin-console.editor'],
  guest: ['file-server.viewer', 'project.viewer', 'admin-console.viewer'],
};
